apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: desafio-app-cert
  namespace: ingress-nginx
spec:
  secretName: desafio-app-tls
  duration: 8760h # 1 año
  renewBefore: 360h # 15 días antes
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: desafio.local
  dnsNames:
    - desafio.local
