name: CI/CD Plataform setup

on:
  workflow_dispatch:

jobs:
  deploy-platform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name gr-dev-cluster

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.9.0'

      - name: Deploy Helm components
        run: |
          cd infra/helm-components
          chmod +x utils.sh deploy.sh
          ./deploy.sh