name: CI/CD Plataform setup

on:
  workflow_dispatch:

jobs:
  deploy-helm-components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Add Helm repositories
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name gr-dev-cluster

      - name: Test cluster connection
        run: |
          kubectl get nodes

      - name: Deploy Helm components
        run: |
          cd infra/helm-components
          chmod +x deploy.sh
          ./deploy.sh

      - name: Wait for cert-manager CRDs
        run: |
          echo "Esperando que los CRDs de cert-manager estén disponibles..."
          kubectl wait --for condition=Established --timeout=120s crd/clusterissuers.cert-manager.io

      - name: Apply cluster-issuer
        run: |
          kubectl apply -f infra/helm-components/cluster-issuer.yaml
