name: Deploy Helm Components

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/helm-components/**'
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EKS via Helm
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name gr-dev-cluster --region us-east-1

      - name: Deploy Helm components
        run: |
          cd infra/helm-components
          chmod +x deploy.sh
          ./deploy.sh
