name: Pipeline despliegue

on:
  push:
    branches: [master]

jobs:
  build-test:
    uses: ./.github/workflows/template-build-test.yaml

  docker:
    needs: build-test
    uses: ./.github/workflows/template-build-image.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    with:
      AWS_REGION: ${{ vars.AWS_REGION }}

  kustomize:
    needs: docker
    uses: ./.github/workflows/template-kustomization.yaml

  deploy:
    needs: kustomize
    uses: ./.github/workflows/template-deploy.yaml
    secrets:
      TEST_S: ${{ secrets.TEST_S }}
    with:
      TEST: ${{ vars.TEST }}    