name: CI/CD Deploy

on:
  push:
    branches: [master]

jobs:
  build-test:
    uses: ./.github/workflows/template-build-test.yaml

  docker:
    needs: build-test
    uses: ./.github/workflows/template-build-image.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    with:
      AWS_REGION: ${{ vars.AWS_REGION }}

  kustomize:
    needs: docker
    uses: ./.github/workflows/template-kustomization.yaml

  deploy-dev:
    uses: ./.github/workflows/template-deploy.yaml
    if: github.ref == 'refs/heads/master'
    with:
      env_path: "dev"
      namespace: "desafio-app"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-prod:
    uses: ./.github/workflows/template-deploy.yaml
    if: github.ref == 'refs/heads/main'
    with:
      env_path: "prod"
      namespace: "desafio-app"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}