name: CI/CD Deploy

on:
  push:
    branches: [master]

jobs:
  build-test:
    uses: ./.github/workflows/template-build-test.yaml

  docker:
    needs: build-test
    uses: ./.github/workflows/template-build-image.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    with:
      AWS_REGION: ${{ vars.AWS_REGION }}

  kustomize:
    needs: docker
    uses: ./.github/workflows/template-kustomization.yaml

  deploy:
    uses: ./.github/workflows/template-deploy.yaml
    with:
      env_path: "k8s/dev"
      namespace: "desafio-app"