name: CI/CD Plataform setup

on:
  workflow_dispatch:

jobs:
  deploy-helm-components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Update kubeconfig using IRSA ServiceAccount (kubectl IRSA)
        run: |
          aws eks update-kubeconfig --region us-east-1 --name gr-dev-cluster

      - name: Patch default SA to use IRSA role (only first time)
        run: |
          kubectl annotate serviceaccount default \
            -n kube-system \
            eks.amazonaws.com/role-arn=arn:aws:iam::027188235773:role/eks-irsa-kubectl \
            --overwrite || true

      - name: Wait for SA update (optional but recommended)
        run: sleep 10

      - name: Test cluster connection
        run: |
          kubectl get nodes

      - name: Deploy Helm components
        run: |
          cd infra/helm-components
          chmod +x deploy.sh
          ./deploy.sh
