name: CI/CD Infrastructure

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Execute Terraform apply?'
        required: true
        default: 'false'

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="environments/dev/dev.tfvars"             

  apply:
    name: Terraform Apply
    needs: terraform
    runs-on: ubuntu-latest
    if: github.event.inputs.apply == 'true'

    defaults:
      run:
        working-directory: infra/terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region us-east-1 --name gr-dev-cluster


      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="environments/dev/dev.tfvars"
