# .github/workflows/template-deploy.yaml
name: Template - Kustomize Deploy

on:
  workflow_call:
    inputs:
      env_path:
        required: true
        type: string
      namespace:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name gr-dev-cluster

      - name: Set up Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Create namespace if needed
        run: |
          kubectl get namespace ${{ inputs.namespace }} || kubectl create namespace ${{ inputs.namespace }}

      - name: Deploy with Kustomize
        run: |
          kustomize build ${{ inputs.env_path }} | kubectl apply -n ${{ inputs.namespace }} -f -
